services:
    mariadb:
        image: mariadb:10
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=cinema
            - MYSQL_USER=cinema
            - MYSQL_PASSWORD=cinema
        ports:
            - 3306:3306
