version: "3.7"
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASENAME: db
      DB_DIALECT: mariadb
      JWT_SECRET: secret
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - db

  adminer:
      image: adminer
      ports:
        - 8080:8080
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
